'use client';

/* eslint-disable @next/next/no-html-link-for-pages */

import Image from 'next/image';
import { CalendarDays, Download, Package, Percent, RotateCcw, ShoppingBag, TrendingUp } from 'lucide-react';
import { useAdminDemo } from '@/context/AdminDemoContext';
import type { DashboardMetric } from '@/lib/admin/types';
import { MetricCard } from './ui/MetricCard';
import { StatusBadge, type StatusTone } from './ui/StatusBadge';
import { AdminCard } from './ui/AdminCard';

const metricIcons: Record<DashboardMetric['icon'], typeof TrendingUp> = { revenue: TrendingUp, orders: ShoppingBag, basket: Package, returns: RotateCcw };
const statusTones: Record<string, StatusTone> = { 'Payée': 'success', 'Expédiée': 'info', 'En préparation': 'warning', 'Annulée': 'danger' };

function SalesChart() {
  return <div className="mt-5 h-[260px] w-full"><svg aria-label="Évolution des ventes" viewBox="0 0 800 260" className="h-full w-full overflow-visible"><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#111" stopOpacity=".12"/><stop offset="1" stopColor="#111" stopOpacity="0"/></linearGradient></defs>{[30,90,150,210].map((y) => <line key={y} x1="48" x2="780" y1={y} y2={y} stroke="#e7e4de" />)}<path d="M48 180 C90 80 120 210 175 150 S250 210 310 120 S390 190 445 100 S515 145 565 55 S630 140 680 105 S730 210 780 95 L780 230 L48 230 Z" fill="url(#salesFill)"/><path d="M48 180 C90 80 120 210 175 150 S250 210 310 120 S390 190 445 100 S515 145 565 55 S630 140 680 105 S730 210 780 95" fill="none" stroke="#111" strokeWidth="4" strokeLinecap="round"/></svg></div>;
}

export function DashboardOverview() {
  const { state, setPeriod } = useAdminDemo();
  return <div className="mx-auto max-w-[1450px]">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm text-admin-muted">Administration&nbsp; / &nbsp;<b className="text-admin-text">Vue d’ensemble</b></p><h1 className="mt-6 text-3xl font-semibold tracking-tight sm:text-4xl">Bonjour Jean</h1><p className="mt-2 text-admin-muted">Voici les performances de votre boutique aujourd’hui.</p></div><div className="flex gap-3"><label className="flex h-11 items-center gap-2 rounded-lg border border-admin-border bg-white px-3 text-sm"><CalendarDays className="size-4" /><span className="sr-only">Période</span><select aria-label="Période" value={state.preferences.period} onChange={(e) => setPeriod(e.target.value as '7d' | '30d' | '90d')} className="bg-transparent outline-none"><option value="7d">7 derniers jours</option><option value="30d">30 derniers jours</option><option value="90d">90 derniers jours</option></select></label><button className="flex h-11 items-center gap-2 rounded-lg border border-admin-border bg-white px-4 text-sm"><Download className="size-4" />Exporter</button></div></div>
    <section aria-label="Indicateurs" className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{state.metrics.map((metric) => <MetricCard key={metric.id} label={metric.label} value={metric.value} trend={metric.trend} positive={metric.positive} icon={metricIcons[metric.icon]} />)}</section>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.8fr_1fr]"><AdminCard className="p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Ventes</h2><div className="flex rounded-lg border border-admin-border p-1 text-xs"><button className="rounded px-3 py-1.5">Jour</button><button className="rounded px-3 py-1.5">Semaine</button><button className="rounded bg-black px-3 py-1.5 text-white">Mois</button></div></div><SalesChart /></AdminCard><AdminCard className="p-5"><h2 className="text-xl font-semibold">Répartition des ventes</h2><div className="mt-8 flex items-center justify-center gap-8"><div className="relative size-40 rounded-full" style={{ background: 'conic-gradient(#111 0 62%, #d7d1c4 62% 86%, #e5e5e5 86%)' }}><div className="absolute inset-9 rounded-full bg-white" /></div><div className="space-y-5 text-sm"><p><span className="mr-3 inline-block size-3 rounded-full bg-black" />Vêtements <b className="ml-3">62 %</b></p><p><span className="mr-3 inline-block size-3 rounded-full bg-[#d7d1c4]" />Accessoires <b className="ml-3">24 %</b></p><p><span className="mr-3 inline-block size-3 rounded-full bg-neutral-200" />Autres <b className="ml-3">14 %</b></p></div></div></AdminCard></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.8fr_1fr]"><AdminCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-admin-border p-5"><h2 className="text-lg font-semibold">Commandes récentes</h2><a href="/fr/commandes" className="text-sm text-blue-600">Voir toutes les commandes</a></div><div className="divide-y divide-admin-border">{state.recentOrders.map((order) => <div key={order.id} className="grid grid-cols-[.7fr_1.3fr_auto] items-center gap-3 p-4 text-sm sm:grid-cols-[.7fr_1.2fr_1fr_.8fr_.7fr]"><b>#{order.id}</b><span><b className="block">{order.customer}</b><small className="text-admin-muted">{order.email}</small></span><span className="hidden sm:block">{order.date}</span><StatusBadge tone={statusTones[order.status]}>{order.status}</StatusBadge><b className="hidden text-right sm:block">{order.total}</b></div>)}</div></AdminCard><div className="grid gap-4"><AdminCard><div className="flex items-center justify-between border-b border-admin-border p-5"><h2 className="font-semibold">Alertes stock</h2><a href="/fr/produits" className="text-sm text-blue-600">Voir tout</a></div><div className="divide-y divide-admin-border">{state.stockAlerts.map((item) => <div key={item.id} className="flex items-center gap-3 p-4"><div className="relative size-14 overflow-hidden rounded bg-admin-soft"><Image src={item.image} alt="" fill className="object-contain" /></div><div className="min-w-0 flex-1"><b className="block truncate text-sm">{item.name}</b><span className="text-xs text-admin-muted">SKU: {item.sku}</span></div><b className="text-sm text-admin-warning">{item.remaining} restants</b></div>)}</div></AdminCard><AdminCard className="p-5"><h2 className="font-semibold">Actions rapides</h2><div className="mt-4 grid gap-2 sm:grid-cols-3 xl:grid-cols-1 2xl:grid-cols-3"><a href="/fr/produits" className="flex items-center gap-2 rounded-lg border border-admin-border p-3 text-xs"><Package className="size-4" />Ajouter un produit</a><button className="flex items-center gap-2 rounded-lg border border-admin-border p-3 text-xs"><Percent className="size-4" />Créer une remise</button><a href="/fr/retours" className="flex items-center gap-2 rounded-lg border border-admin-border p-3 text-xs"><RotateCcw className="size-4" />Traiter un retour</a></div></AdminCard></div></div>
  </div>;
}
