'use client';

/* eslint-disable @next/next/no-img-element */

import { useState, type FormEvent } from 'react';
import { ArrowRight, Eye, EyeOff, LockKeyhole, ShieldCheck, UserRound } from 'lucide-react';

export function LoginPanel({ locale }: { locale: 'fr' | 'en' }) {
  const fr = locale === 'fr';
  const [show, setShow] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (!data.get('email') || !data.get('password')) { setError(fr ? 'Veuillez renseigner tous les champs.' : 'Please complete every field.'); return; } setLoading(true); window.setTimeout(() => { window.location.href = `/${locale}/dashboard`; }, 600); };
  return <div className="flex min-h-screen bg-[#fbfaf7]">
    <section className="relative hidden w-1/2 overflow-hidden bg-black text-white lg:block"><img src="/image/reign-admin-hoodie.png" alt="Hoodie noir Reign suspendu" className="absolute inset-0 h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-black/35 via-transparent to-transparent" /><div className="relative flex h-full flex-col justify-between p-14"><div><p className="font-serif text-[44px] tracking-[.16em]">REIGN</p><p className="text-xs font-semibold tracking-[.3em]">ADMINISTRATION</p></div><div className="max-w-xl pb-14"><p className="text-sm font-semibold tracking-[.25em]">REIGN BACK OFFICE</p><h1 className="mt-6 font-serif text-6xl leading-[1.08]">Pilotez votre boutique<br />avec précision.</h1><p className="mt-5 max-w-lg text-lg leading-relaxed text-white/80">Produits, commandes, retours et conversations clients réunis dans un seul espace sécurisé.</p><p className="mt-10 flex items-center gap-4 text-sm"><ShieldCheck className="size-7" />Accès réservé aux membres autorisés.</p></div></div></section>
    <section className="relative flex min-h-screen flex-1 items-center justify-center px-6 py-12"><a href={fr ? '/en/connexion' : '/fr/connexion'} className="absolute right-7 top-6 text-sm">{fr ? 'FR' : 'EN'}⌄</a><div className="w-full max-w-[570px]"><div className="text-center"><div className="font-serif text-6xl">R</div><h2 className="mt-3 font-serif text-5xl">{fr ? 'Connexion' : 'Sign in'}</h2><p className="mt-2 text-admin-muted">{fr ? "Accédez à votre espace d’administration." : 'Access your administration space.'}</p></div>
      <form onSubmit={submit} className="mt-10 space-y-5" noValidate>{error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="block"><span className="mb-2 block text-sm font-semibold">{fr ? 'Identifiant' : 'Username'}</span><span className="flex h-16 items-center gap-4 rounded-lg border border-neutral-900 bg-white px-5 shadow-sm"><UserRound className="size-6 stroke-[1.5]" /><input name="email" type="email" className="w-full bg-transparent outline-none" placeholder={fr ? "Email ou nom d’utilisateur" : 'Email or username'} /></span></label>
      <label className="block"><span className="mb-2 block text-sm font-semibold">{fr ? 'Mot de passe' : 'Password'}</span><span className="flex h-16 items-center gap-4 rounded-lg border border-admin-border bg-white px-5"><LockKeyhole className="size-6 stroke-[1.5]" /><input aria-label={fr ? 'Mot de passe' : 'Password'} name="password" type={show ? 'text' : 'password'} className="w-full bg-transparent outline-none" placeholder="••••••••••••" /><button type="button" aria-label={show ? 'Masquer le mot de passe' : 'Afficher le mot de passe'} onClick={() => setShow(!show)}>{show ? <EyeOff className="size-6" /> : <Eye className="size-6" />}</button></span></label>
      <div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2"><input type="checkbox" className="size-5 accent-black" />{fr ? 'Se souvenir de moi' : 'Remember me'}</label><a href="#forgot" className="underline underline-offset-4">{fr ? 'Mot de passe oublié ?' : 'Forgot password?'}</a></div><button disabled={loading} className="flex h-16 w-full items-center justify-center gap-3 rounded-lg bg-black font-semibold tracking-[.14em] text-white disabled:opacity-60">{loading ? (fr ? 'CONNEXION...' : 'SIGNING IN...') : (fr ? 'SE CONNECTER' : 'SIGN IN')}<ArrowRight className="size-5" /></button></form>
      <p className="mt-5 flex items-center justify-center gap-2 text-sm text-admin-muted"><LockKeyhole className="size-4" />{fr ? 'Connexion sécurisée et chiffrée.' : 'Secure encrypted connection.'}</p><div className="mt-7 border-t border-admin-border pt-6"><p className="text-sm"><b>{fr ? "Besoin d’aide ?" : 'Need help?'}</b> <a href="mailto:support@reign.com" className="ml-5 underline">{fr ? "Contacter l’administrateur" : 'Contact administrator'}</a></p><div className="mt-5 flex gap-4 rounded-lg border border-admin-border bg-[#f7f5f0] p-5 text-sm"><ShieldCheck className="size-7 shrink-0" /><p>{fr ? "L’authentification à deux facteurs peut être demandée après la connexion." : 'Two-factor authentication may be required after sign in.'}</p></div></div><footer className="mt-10 flex justify-between text-xs text-admin-muted"><span>© 2026 Reign</span><span className="flex gap-6"><a href={`/${locale}/confidentialite`} className="underline">Confidentialité</a><a href={`/${locale}/mentions-legales`} className="underline">Sécurité</a></span></footer></div></section>
  </div>;
}
